apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cortex
  namespace: cortex
spec:
  chart:
    spec:
      version: "0.6.0"
  values:
    ingress:
      hosts:
        - host: cortex.production
          paths:
            - path: /
