apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cortex
  namespace: cortex
spec:
  chart:
    spec:
      version: ">=0.6.0"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: cortex.staging
          paths:
            - path: /
